title: ../root
description: Hack the planet; | Security Researcher | Bug hunter
show_downloads: false

theme: jekyll-theme-hacker

avatar: ../images/logo.jpeg
footer-links:
  twitter: Moustafa0x04


disqus:
url:
baseurl: ""
permalink: #/:title/
version: v1.1.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded # You might prefer to minify using :compressed
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-admin

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
